/**
 * Pre-filled sample data extracted directly from all 3 photos of the paper chart.
 * Contains Dönüş 1 (30/30), Dönüş 2 (30/30), and Dönüş 3 (15/30 up to 19.08.2026).
 */

const PHOTO_SAMPLE_DATA = {
  activeRoundId: "round_photo_3",
  rounds: [
    {
      id: "round_photo_1",
      name: "1. Dönüş",
      createdDate: "2026-06-05",
      juzs: [
        { id: 1, name: "1. Cüz", date: "2026-06-05", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 2, name: "2. Cüz", date: "2026-06-06", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 3, name: "3. Cüz", date: "2026-06-08", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 4, name: "4. Cüz", date: "2026-06-09", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 5, name: "5. Cüz", date: "2026-06-10", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 6, name: "6. Cüz", date: "2026-06-11", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 7, name: "7. Cüz", date: "2026-06-12", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 8, name: "8. Cüz", date: "2026-06-13", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 9, name: "9. Cüz", date: "2026-06-13", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 10, name: "10. Cüz", date: "2026-06-14", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 11, name: "11. Cüz", date: "2026-06-16", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 12, name: "12. Cüz", date: "2026-06-17", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 13, name: "13. Cüz", date: "2026-06-18", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 14, name: "14. Cüz", date: "2026-06-19", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 15, name: "15. Cüz", date: "2026-06-21", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 16, name: "16. Cüz", date: "2026-06-23", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 17, name: "17. Cüz", date: "2026-06-24", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 18, name: "18. Cüz", date: "2026-06-25", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 19, name: "19. Cüz", date: "2026-06-25", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 20, name: "20. Cüz", date: "2026-06-26", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 21, name: "21. Cüz", date: "2026-06-27", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 22, name: "22. Cüz", date: "2026-06-27", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 23, name: "23. Cüz", date: "2026-06-29", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 24, name: "24. Cüz", date: "2026-06-30", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 25, name: "25. Cüz", date: "2026-07-01", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 26, name: "26. Cüz", date: "2026-07-02", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 27, name: "27. Cüz", date: "2026-07-02", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 28, name: "28. Cüz", date: "2026-07-03", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 29, name: "29. Cüz", date: "2026-07-06", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 30, name: "30. Cüz", date: "2026-07-06", teacher: "Muhammed Hoca", status: "completed", note: "" }
      ]
    },
    {
      id: "round_photo_2",
      name: "2. Dönüş",
      createdDate: "2026-07-07",
      juzs: [
        { id: 1, name: "1. Cüz", date: "2026-07-07", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 2, name: "2. Cüz", date: "2026-07-08", teacher: "Muhammed Hoca", status: "completed", note: "" },
        { id: 3, name: "3. Cüz", date: "2026-07-09", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 4, name: "4. Cüz", date: "2026-07-10", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 5, name: "5. Cüz", date: "2026-07-10", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 6, name: "6. Cüz", date: "2026-07-11", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 7, name: "7. Cüz", date: "2026-07-12", teacher: "Yusuf Hoca", status: "completed", note: "" },
        { id: 8, name: "8. Cüz", date: "2026-07-14", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 9, name: "9. Cüz", date: "2026-07-15", teacher: "Yusuf Hoca", status: "completed", note: "" },
        { id: 10, name: "10. Cüz", date: "2026-07-17", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 11, name: "11. Cüz", date: "2026-07-18", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 12, name: "12. Cüz", date: "2026-07-18", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 13, name: "13. Cüz", date: "2026-07-19", teacher: "Malik Abim", status: "completed", note: "" },
        { id: 14, name: "14. Cüz", date: "2026-07-20", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 15, name: "15. Cüz", date: "2026-07-21", teacher: "Enes Hocam", status: "completed", note: "" },
        { id: 16, name: "16. Cüz", date: "2026-07-22", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 17, name: "17. Cüz", date: "2026-07-23", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 18, name: "18. Cüz", date: "2026-07-24", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 19, name: "19. Cüz", date: "2026-07-25", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 20, name: "20. Cüz", date: "2026-07-26", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 21, name: "21. Cüz", date: "2026-07-27", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 22, name: "22. Cüz", date: "2026-07-28", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 23, name: "23. Cüz", date: "2026-07-29", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 24, name: "24. Cüz", date: "2026-07-30", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 25, name: "25. Cüz", date: "2026-07-30", teacher: "Yusuf Hoca", status: "completed", note: "" },
        { id: 26, name: "26. Cüz", date: "2026-07-31", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 27, name: "27. Cüz", date: "2026-08-02", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 28, name: "28. Cüz", date: "2026-08-03", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 29, name: "29. Cüz", date: "2026-08-04", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 30, name: "30. Cüz", date: "2026-08-04", teacher: "Metin Hocam", status: "completed", note: "" }
      ]
    },
    {
      id: "round_photo_3",
      name: "3. Dönüş",
      createdDate: "2026-08-05",
      juzs: [
        { id: 1, name: "1. Cüz", date: "2026-08-05", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 2, name: "2. Cüz", date: "2026-08-07", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 3, name: "3. Cüz", date: "2026-08-08", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 4, name: "4. Cüz", date: "2026-08-10", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 5, name: "5. Cüz", date: "2026-08-10", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 6, name: "6. Cüz", date: "2026-08-11", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 7, name: "7. Cüz", date: "2026-08-12", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 8, name: "8. Cüz", date: "2026-08-13", teacher: "Metin Hocam", status: "completed", note: "" },
        { id: 9, name: "9. Cüz", date: "2026-08-13", teacher: "Yusuf Alagöz H.", status: "completed", note: "" },
        { id: 10, name: "10. Cüz", date: "2026-08-14", teacher: "Yusuf Alagöz H.", status: "completed", note: "" },
        { id: 11, name: "11. Cüz", date: "2026-08-15", teacher: "Yusuf Hocam", status: "completed", note: "" },
        { id: 12, name: "12. Cüz", date: "2026-08-17", teacher: "Yusuf Hocam", status: "completed", note: "" },
        { id: 13, name: "13. Cüz", date: "2026-08-17", teacher: "Yusuf Hocam", status: "completed", note: "" },
        { id: 14, name: "14. Cüz", date: "2026-08-18", teacher: "Yusuf Hocam", status: "completed", note: "" },
        { id: 15, name: "15. Cüz", date: "2026-08-19", teacher: "Yusuf Hocam", status: "completed", note: "" },
        { id: 16, name: "16. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 17, name: "17. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 18, name: "18. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 19, name: "19. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 20, name: "20. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 21, name: "21. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 22, name: "22. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 23, name: "23. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 24, name: "24. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 25, name: "25. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 26, name: "26. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 27, name: "27. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 28, name: "28. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 29, name: "29. Cüz", date: "", teacher: "", status: "empty", note: "" },
        { id: 30, name: "30. Cüz", date: "", teacher: "", status: "empty", note: "" }
      ]
    }
  ]
};
